plugins {
    kotlin("jvm") version "2.1.21"
    application
    id("com.gradleup.shadow") version "8.3.6"
    jacoco
}

group = "krmelin"
version = "0.1.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.github.ajalt.clikt:clikt:4.4.0")
    // In-process Kotlin compilation for `compile --jar` and `run` (M4): no kotlinc on
    // PATH is required. Keeps the fat jar self-contained, same philosophy as PorubaUnit.
    implementation("org.jetbrains.kotlin:kotlin-compiler-embeddable:2.1.21")
    testImplementation(kotlin("test"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

application {
    mainClass.set("krmelin.MainKt")
}

tasks.test {
    useJUnitPlatform()
    // Golden tests regenerate expected files with -Dupdate.golden=true (Plan.md §9).
    systemProperty("update.golden", System.getProperty("update.golden") ?: "false")
    // E2e tests shell out to the fat jar (krmelin run/compile).
    dependsOn(tasks.shadowJar)
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

tasks.jacocoTestCoverageVerification {
    dependsOn(tasks.test)
    violationRules {
        rule {
            element = "PACKAGE"
            includes = listOf(
                "krmelin.lexer",
                "krmelin.parser",
                "krmelin.resolve",
                "krmelin.types",
                "krmelin.lower",
                "krmelin.codegen",
            )
            limit {
                minimum = "0.90".toBigDecimal()
            }
        }
    }
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    archiveBaseName.set("krmelin")
    archiveClassifier.set("")
    archiveVersion.set(version.toString())
    mergeServiceFiles()
}

// Rename the plain jar so it does not collide with the shadow jar output file.
tasks.named<Jar>("jar") {
    archiveClassifier.set("slim")
}

// The Gradle `version` above is the single source of truth for `krmelin --version`.
// It is baked into a generated source file rather than read from the jar manifest,
// because the manifest is absent when running off Gradle's loose-class test classpath.
val generateBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildinfo")
    val projectVersion = version.toString()
    inputs.property("version", projectVersion)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("krmelin")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildInfo.kt").writeText(
            """
            package krmelin

            /** Generated by the `generateBuildInfo` Gradle task — do not edit by hand. */
            internal object BuildInfo {
                const val VERSION: String = "$projectVersion"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(21)
    // Passing the task provider (not the bare path) carries the build dependency with it.
    sourceSets["main"].kotlin.srcDir(generateBuildInfo)
}
